from ssqlalchemy import create_enginge
import pandas as pd 
engine=cerate_engine('mysql+pymysql://root:1234@127.0.0.1:\3306/testdb?charset=utf8')
detail=pd.read_sql_table('meal_order_detail',con=engine)
print(detail1.index)
print(detail.values)
print(detail.columns)
print(detail.detypes)
print(detail.size)
print(detail.ndim)
print(detail.shape)
print(detail.T.shape)
order_id=detail['order_id']
print(order_id.shape)
dishesname=detail.dishes_name
print(dishes_name.shape)
dishes_name5=detail['dishes_name'][:5]
print(dishes_name5)
orderdish=detail[['order_id','dishes_name']][:5]
print(orderdish)
order5=detail[:][1:6]
print(order5)
print(detail.head())
print(detail.tail())

dishes_name1=detail.loc[:,'dishes_name']
print(dishes_name1.size)
dishes_name2=detail.iloc[:,3]
print(dishes_name2.size)
orderdish1=detail.loc[:,['order_id','dishes_name']]
print(orderdish1.size)
orderdish2=detail.iloc[:,[1,3]]
print(orderdish2)
print(detail.loc[3,['order_id','dishes_name']])
print(detail.loc[2:6,['order_id','dishes_name']])
print(detail.iloc[3,[1,3]])
print(detail.iloc[2:6,[1,3]])
print(detail.loc[detail['order_id']=='458',['order_id','dishes_name']])
print(detail.iloc[detail['order_id']=='458',[1,5]])         #错误行出只返回一个false或者true
print(detail.iloc[(detail['order_id']=='458').values,[1,5]])
print(detail.loc[2:6,'dishes_name'])
print(detail.iloc[2:6,5])
print(detail.ix[2:6,5])
